classdef ActuatorControl < robotics.ros.Message
    %ActuatorControl MATLAB implementation of mavros_msgs/ActuatorControl
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2016 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/ActuatorControl' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '9eea0a80c88944fe2fb67f3b3768854b' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        PX4MIXFLIGHTCONTROL = uint8(0)
        PX4MIXFLIGHTCONTROLVTOLALT = uint8(1)
        PX4MIXPAYLOAD = uint8(2)
        PX4MIXMANUALPASSTHROUGH = uint8(3)
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        GroupMix
        Controls
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Controls', 'GroupMix', 'Header'} % List of non-constant message properties
        ROSPropertyList = {'controls', 'group_mix', 'header'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ActuatorControl(msg)
            %ActuatorControl Construct the message object ActuatorControl
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                obj.initializeFixedArrays;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                obj.initializeFixedArrays;
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
                obj(i,1).initializeFixedArrays;
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ActuatorControl', 'header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function groupmix = get.GroupMix(obj)
            %get.GroupMix Get the value for property GroupMix
            groupmix = typecast(int8(obj.JavaMessage.getGroupMix), 'uint8');
        end
        
        function set.GroupMix(obj, groupmix)
            %set.GroupMix Set the value for property GroupMix
            validateattributes(groupmix, {'numeric'}, {'nonempty', 'scalar'}, 'ActuatorControl', 'groupmix');
            
            obj.JavaMessage.setGroupMix(groupmix);
        end
        
        function controls = get.Controls(obj)
            %get.Controls Get the value for property Controls
            javaArray = obj.JavaMessage.getControls;
            array = obj.readJavaArray(javaArray, 'single');
            controls = single(array);
        end
        
        function set.Controls(obj, controls)
            %set.Controls Set the value for property Controls
            validateattributes(controls, {'numeric'}, {'vector', 'numel', 8}, 'ActuatorControl', 'controls');
            
            javaArray = obj.JavaMessage.getControls;
            array = obj.writeJavaArray(controls, javaArray, 'single');
            obj.JavaMessage.setControls(array);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function initializeFixedArrays(obj)
            %initializeFixedArrays Correctly initialize fixed-size arrays
            
            obj.Controls = robotics.ros.Message.initializeFixedArray(obj.Controls, 8);
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.GroupMix = obj.GroupMix;
            cpObj.Controls = obj.Controls;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.GroupMix = strObj.GroupMix;
            obj.Controls = strObj.Controls;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.GroupMix = obj.GroupMix;
            strObj.Controls = obj.Controls;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.ActuatorControl.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.ActuatorControl;
            obj.reload(strObj);
        end
    end
end
