% MSS HYDRO - Version 1.1 (Matlab R2007, R2008, R2009)
%
% MSS HYDRO is a Matlab/Simulink toolbox for hydrodynamic post-processing and
% time-domain simulation of data generated by ShipX, WAMIT and SeaWay which
% are commercial codes which need to be purchased separately.
%
% The toolbox is part of the Marine Systems Simulator (MSS).
%
% Copyright (C) 2008-2009 Thor I. Fossen and Tristan Perez
% 
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
% 
% E-mail: contact@marinecontrol.org
% URL:    <http://www.marinecontrol.org>
%
% --------------------------------------------------------------------------- 
% Required Software:
%
% 1) Simulink and MSS GNC is needed to run the Simulink templates/demos.
%
% 2) The toolbox includes example vessel data for the following vessels: 
%
%    ShipX (VERES): S175, SUPPLY
%    WAMIT        : TANKER, FPSO, SEMI-SUB
%    SeaWay       : TUGBOAT
%
% In order to generate NEW vessel data, the user must have a valid license
% of one of the following programs: ShipX (VERES) by Marintek www.sintef.no,
% Octopus SEAWAY by www.amarcon.com, or WAMIT by www.wamit.com.
%
% 3) Hydrodynamic processing/computation of fluid memory effects
% (vessel2ss.m) requires the Control System Toolbox and Robust Control
% Toolbox in Matlab  
% 
% ----------------------------------------------------------------------------
% MSS Hydro Simulink Templates: 
% ----------------------------------------------------------------------------
% ...\mss\hydro\simulink\
%
% DP_MotionRAO - Zero speed DP model using motion RAOs
% DP_ForceRAO  - Zero speed DP model using force RAOs
% MAN_ForceRAO - Forward speed maneuvering model using force RAOs
% 
% ----------------------------------------------------------------------------
% MSS Hydro M-File Library:   ...\mss\hydro\hydro_mfiles\
% ----------------------------------------------------------------------------
% Generation of the MSS 'vessel' structure (input to Simulink model):
%
%   veres2vessel  - generates the MSS vessel structure from the Shipx
%                   (VERES) data files *.re1, *.re2, *re7, *re8, and *.hyd
%   wamit2vessel  - generates the MSS vessel structure from the WAMIT
%                   data files *.frc, *out, *.N where N = {1,2,3,4,8,9}
%
% Generation of the MSS 'vesselABC' structure from the 'vessel' structure
% (input to Simulink model):
%
%   vessel2ss     - generates state-space models/retardation functions
%
% Functions to process and visualize hydrodynamic data:
%
%   DPperiods     - compute time constants and periods for zero speed
%   loadcond      - plot vessel load condition/GM_T sensitivity in roll
%   plotABC       - plots hydrodynamic A,B and C data
%   plotTF        - plots force and motion RAOs
%   plotWD        - plots mean wave drift forces
%
% ----- FDI file library  ...\mss\hydro\hydro_mfiles\FDI\----------------------
%
%   FDIRadMod     - frequency identification of radiation forces/fluid memory
%
% ----- Wamit GDF file library ...\mss\hydro\hydro_mfiles\gdf\ ---------------
%
%   plot_wamitgdf - plot WAMIT GDF file generated from VERES
%   plot_wamitidf - plot WAMIT IDF file incl. autogenerated free surface (IRR=3)
%   plot_tecplot  - plot WAMIT generated Tecplot files (for semisubs)
%   gdf2body      - transform the GDF file from global coordinates (Lpp/2,B/L,WL)
%                   to body-fixed CG
%
% ----- Utility m-files:  ...\mss\hydro\hydro_mfiles\utils -------------------
%
%   ABCtransform   - transform hydrodynamic coefficients
%   fit_siso_fresp - state-space model indentification in the frequency-domain
%   Hoerner        - 2D Hoerner cross-flow form coefficient as function of B and T
%   viscous        - computes a constant viscous damping matrix for time-domain simulation
%   mss_interp2    - interpolation routine used to interpolate A and B data
%   retardation    - computes the fluid memory effect retardation functions
%   retardation2ss - state-space model identification in the time-domain
%
% ----------------------------------------------------------------------------